# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: required

r_check_args: '--use-valgrind'

addons:
  apt:
    packages:
      - valgrind

env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'

before_script:
  - echo 'sudo mv ./.valgrindrc $HOME'
