# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Red flag
#'
#' This function introduces a memory leak that is supposed to trigger
#' valgrind and throw and error in R CMD check.
#'
#' @return Stuff.
#'
#' @examples
#' replicate(ouch(), 10)
#'
#' @export
ouch <- function() {
    .Call('valgrindtestr_ouch', PACKAGE = 'valgrindtestr')
}

