# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Red flag
#'
#' This function introduces a memory leak that is supposed to trigger
#' valgrind and throw an error in R CMD check.
#'
#' @return Stuff.
#'
#' @examples
#' mistake()
#'
#' @export
mistake <- function() {
    .Call('valgrindtestr_mistake', PACKAGE = 'valgrindtestr')
}

